### ISSUE TITLE
Replacing wordpress i18n package?

### ISSUE THREAD

**Issue by vonloxx** [front/gutenberg-js#10]
I'm wondering if we could replace wordpress i18n package for something custom. I'm thinking about the Drupal implementation: on browser side, Drupal uses a javascript method Drupal.t() for translations.
It would be nice if we could override wp's __() translation function before the editor is initialized.

**Comment by Qoraiche** [comment]
Hi @vonloxx, I'm sorry that I don't have an answer to your question. but, can I ask you how you implement WordPress i18n package in gutenberg-js?, I want to change to another language. thanks

**Comment by Qoraiche** [comment]
thanks, @SofiaSousa, I will try this soon!

**Comment by QiShaoXuan** [comment]
@SofiaSousa @Qoraiche 
Is there any demo to view the detail code ? I really didn't try any thing about it. Thank you very much

**Comment by SofiaSousa** [comment]
Hi @QiShaoXuan,

I think we don't have it yet. I've created https://github.com/front/g-editor/issues/5 suggesting the translations implementation in [g-editor](https://github.com/front/g-editor).

**Comment by QiShaoXuan** [comment]
> Hi @QiShaoXuan,
> 
> I think we don't have it yet. I've created [front/g-editor#5](https://github.com/front/g-editor/issues/5) suggesting the translations implementation in [g-editor](https://github.com/front/g-editor).

it is so sad but thank you , and one more question, do you have any thinking to solve it？

**Comment by QiShaoXuan** [comment]
> Hi @QiShaoXuan,
> 
> I think we don't have it yet. I've created [front/g-editor#5](https://github.com/front/g-editor/issues/5) suggesting the translations implementation in [g-editor](https://github.com/front/g-editor).

it is so sad but thank you, and one more question, can I use

**Comment by SofiaSousa** [comment]
> do you have any thinking to solve it?

Sorry, I didn't understand, to solve what?

**Comment by KuzNet** [comment]
> import { i18n } from '@frontkom/gutenberg-js';

> import { i18n } from '@frontkom/gutenberg-js'; import translations from './translations';
> 
> const { setLocaleData, __, _n, sprintf } = i18n; setLocaleData(translations);
> 
> console.log(**('User')); console.log(**('Action'));
> 
> const num = 3; console.log(sprintf(_n('%d result', '%d results', num), num));

@eliocro
