### ISSUE TITLE
Guternberg latest version

### ISSUE THREAD

**Issue by MDSilviu** [front/gutenberg-js#15]
Will this package be upgraded to the latest version of gutenberg? Is there any plan in doing that?

**Comment by perandre** [comment]
Yes, it will – continually. However, we will not do any updates until after X-mas.

**Comment by epoleacov** [comment]
Any news?

**Comment by eliocro** [comment]
Please check my comment on a separate issue:
https://github.com/front/gutenberg-js/issues/32#issuecomment-497333673
