### ISSUE TITLE
Cannot read property 'createContext' of undefined

### ISSUE THREAD

**Issue by dragonfire1119** [front/gutenberg-js#16]
I keep getting ``Cannot read property 'createContext' of undefined`` I'm following the readme but it just doesn't seem to be working. I'm also loading them in order by example: https://github.com/front/g-editor/blob/master/package.json Thanks for any help.

UPDATE: I was trying to add the dependencies without
```
<script src="https://unpkg.com/react@16.6.3/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.6.3/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/moment@2.22.1/min/moment.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
```
adding these to the head but it seems like you can't.

Now the error is ``TypeError: Cannot read property 'indexOf' of undefined`` in the gutenberg.js file something to do with the apiFetch.

gutenberg-js: 3.0.1
react: 16.6.3
react-dom: 16.6.3

**Comment by chaseWillden** [comment]
@dragonfire1119 how did you end up solving this anyways? I'm getting the same issue
