### ISSUE TITLE
Production build error (React)

### ISSUE THREAD

**Issue by botoxparty** [front/gutenberg-js#18]
When running a production build I get:

`Uncaught TypeError: Super expression must either be null or a function, not undefined`

 ```
at gutenberg-js.js:6520
    at gutenberg-js.js:6519
    at gutenberg-js.js:6504
    at Object.<anonymous> (gutenberg-js.js:26733)
    at n (gutenberg-js.js:17)
    at Object.<anonymous> (gutenberg-js.js:82448)
    at n (gutenberg-js.js:17)
    at Object.<anonymous> (gutenberg-js.js:34453)
    at n (gutenberg-js.js:17)
    at Object.<anonymous> (gutenberg-js.js:46974)
```

**Comment by arnvanhoutte** [comment]
I think this is similar to this: https://github.com/front/gutenberg-js/issues/14

**Comment by botoxparty** [comment]
Indeed it is, wouldn't really want to turn off optimisation though.

How would I go about debugging this?

**Comment by arnvanhoutte** [comment]
Have you find a way to fix this?

**Comment by botoxparty** [comment]
No, I would need sourcemaps for gutenberg-js.js

**Comment by arnvanhoutte** [comment]
@SofiaSousa Will this be looked at? Or is this a Wordpress issue?

**Comment by botoxparty** [comment]
I would be happy to work on the development of this to get it production ready @SofiaSousa if you could point me in the direction of source maps for `gutenberg-js.js`

Also I feel like this particular error could have something to do with it not registering that React is loaded?

**Comment by Qoraiche** [comment]
> I would be happy to work on the development of this to get it production ready @SofiaSousa if you could point me in the direction of source maps for `gutenberg-js.js`
> 
> Also I feel like this particular error could have something to do with it not registering that React is loaded?

@botoxparty that's would be great!, I hope you get help.

**Comment by SofiaSousa** [comment]
@botoxparty I'm not sure about what you are asking but you can check the source maps here https://unpkg.com/@frontkom/gutenberg-js@3.0.1/build/js/gutenberg-js.js.map or in gutenberg-js `build` folder after running `npm run build`.

**Comment by Qoraiche** [comment]
@SofiaSousa can you please fix the production error: `Uncaught TypeError: Super expression must either be null or a function, not undefined`.

we will be very thankful

**Comment by SofiaSousa** [comment]
It's probably related with circular dependencies of the @wordpress/gutenberg packages and we probably can't do anything about that in gutenberg-js.

**Comment by botoxparty** [comment]
@SofiaSousa so do you get this same error? Are the current contributors going to continue working on this project or has it been abandoned?

**Comment by Qoraiche** [comment]
@SofiaSousa so there is no way to build? development server works fine for the g-editor but the build doesn't. any trick?

thanks again for your help

**Comment by SofiaSousa** [comment]
As @arnvanhoutte suggested at [g-editor/issues/4](https://github.com/front/g-editor/issues/4):
> At the moment: turning optimizations off.

Project is not abandoned, but solving this is not a priority. If you want to suggest a solution please create a pull request.

**Comment by Qoraiche** [comment]
@SofiaSousaI i think it's Impossible/Difficult to use gutenberg-js in a production environment since the production builds not working!

**Comment by Qoraiche** [comment]
This error has been fixed in the new update of [g-editor](https://github.com/front/g-editor).

**Comment by arnvanhoutte** [comment]
Excuse me if I have been getting this wrong, but the fix there seems to be to turn compression off: https://github.com/front/g-editor/commit/7e742d1e4bd91342d3ac6755a4aa00dae166b3be

I don't really see that as a fix, but more like a temporary workaround

**Comment by Qoraiche** [comment]
@arnvanhoutte , I think they can not fix this issue directly because it's caused circular dependencies inside Gutenberg itself. the only solution is to disable compression on the TerserPlugin.
