### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by arnvanhoutte** [front/gutenberg-js#20]
After updating to 4.0.0-rc.1 I've been getting this error immediately in startup. Building works fine but when opening my app, this error shows up in my console and gutenberg does not load

**Comment by cyberiaa** [comment]
I had the same problem.  I fixed it by installing @babel/plugin-transform-runtime and editing webpack.config.js

```
const babelLoader = {
  loader: 'babel-loader',
  options: {
    presets: ['@babel/preset-react' ],
    plugins: ['@babel/plugin-transform-runtime' //added
]
```

**Comment by arnvanhoutte** [comment]
Indeed, in my case adding Babel-Polyfills also worked.
