### ISSUE TITLE
Contetful + GatsbyJS

### ISSUE THREAD

**Issue by guysherman** [front/gutenberg-js#29]
I am interested in making this work with Contentful. Would it mainly be a matter of adapting the API to the wp API that this expects?

**Comment by eliocro** [comment]
Sorry for the late reply.
We are no longer actively maintaining this project. 
Instead you can check our sister project g-editor (https://github.com/front/g-editor) for an example on how to use the Gutenberg packages directly.

You don't really have to adapt the API itself, just the connector function. Ie. Gutenberg will request a specific WP route, then you can intercept and reply with your API response.
