### ISSUE TITLE
Multiple editors on the same page

### ISSUE THREAD

**Issue by mauricewijnia** [front/gutenberg-js#30]
I am working on a package that makes it easy to use this editor in Laravel.
I was wondering if there is a way to render the editor multiple times on the same page so it could be used for multiple form fields?

Right now I am getting errors about blocks already being registered:
```
Block "core/paragraph" is already registered.
Block "core/image" is already registered.
Block "core/heading" is already registered.
...
```

**Comment by FlusherDock1** [comment]
I tried my best to figure out how to make multiple widgets, but i have same problem or two widgets just sharing one content to each other.
