### ISSUE TITLE
Editor does not seem to render in Angular

### ISSUE THREAD

**Issue by arnvanhoutte** [front/gutenberg-js#8]
I tried implementing Gutenberg-JS in Angular 6+.
The project can be found here: https://github.com/arnvanhoutte/ng-gutenberg

When running the project, the editor does not show up. There aren't any errors in the console either, except a few console.logs from the apiFetch() function

**Comment by SofiaSousa** [comment]
Hi @arnvanhoutte, thanks for giving a chance to Gutenberg-js!

I've checked your repo and in [polyfills.ts](https://github.com/arnvanhoutte/ng-gutenberg/blob/master/src/polyfills.ts#L88) file, you set the `wp.apiFetch` global var but you are not handling with the requests from the editor. The editor expects different responses according the requests. (You can check our [docs](https://github.com/front/gutenberg-js#apifetch) or [The WordPress REST API Handbook](https://developer.wordpress.org/rest-api/reference/))

I think that's the problem. Let me know if it helped.

**Comment by arnvanhoutte** [comment]
Ah indeed. I updated my apiFetch with the example you made for[ g-editor](https://github.com/front/g-editor/blob/master/src/globals/api-fetch.js) and this one works flawlessly. Thank you
